version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: car-price-db
      MYSQL_USER: default
      MYSQL_PASSWORD: default
    volumes:
      - mysql_data:/var/lib/mysql
    stdin_open: true
    tty: true

volumes:
  mysql_data:
